extends Node

const AIR_TWIN_TEXTURE : CompressedTexture2D = preload("res://assets/Side/sketch/air_twin.png")
const AXE_TEXTURE : CompressedTexture2D = preload("res://assets/Side/sketch/incomplete_axe.png")
const CLONE_TEXTURE : CompressedTexture2D = preload("res://assets/Side/sketch/clone.png")
const CLONE_FINAL_TEXTURE : CompressedTexture2D = preload("res://assets/Side/sketch/clone final.png")
const END_HOLD_TEXTURE : CompressedTexture2D = preload("res://assets/Side/sketch/end hold.png")
const GROUND_TWIN_TEXTURE : CompressedTexture2D = preload("res://assets/Side/sketch/ground_twin.png")
const HAMMER_TEXTURE : CompressedTexture2D = preload("res://assets/Side/sketch/incomplete_hammer.png")
const HEART_TEXTURE : CompressedTexture2D = preload("res://assets/Side/sketch/heart.png")
const HEAVY_TEXTURE : CompressedTexture2D = preload("res://assets/Side/sketch/heavy.png")
const LIGHT_1_TEXTURE : CompressedTexture2D = preload("res://assets/Side/sketch/light 1.png")
const LIGHT_2_TEXTURE : CompressedTexture2D = preload("res://assets/Side/sketch/light 2.png")
const LIGHT_3_TEXTURE : CompressedTexture2D = preload("res://assets/Side/sketch/light 3.png")
const MEDIUM_1_TEXTURE : CompressedTexture2D = preload("res://assets/Side/sketch/medium 1.png")
const MEDIUM_2_TEXTURE : CompressedTexture2D = preload("res://assets/Side/sketch/medium 2.png")
const MIDDLE_HOLD_TEXTURE : CompressedTexture2D = preload("res://assets/Side/sketch/middle hold.png")
const NOTE_1_TEXTURE : CompressedTexture2D = preload("res://assets/Side/sketch/note 1.png")
const NOTE_2_TEXTURE : CompressedTexture2D = preload("res://assets/Side/sketch/note 2.png")
const SHIELD_0_TEXTURE : CompressedTexture2D = preload("res://assets/Side/sketch/shield 0.png")
const SHIELD_1_TEXTURE : CompressedTexture2D = preload("res://assets/Side/sketch/shield 1.png")
const SHIELD_2_TEXTURE : CompressedTexture2D = preload("res://assets/Side/sketch/shield 2.png")
const START_HOLD_TEXTURE : CompressedTexture2D = preload("res://assets/Side/sketch/start hold.png")
const TRAP_TEXTURE : CompressedTexture2D = preload("res://assets/Side/sketch/trap.png")
const TWINS_TEXTURE : CompressedTexture2D = preload("res://assets/Side/sketch/twins.png")
